-- CRIAÇÃO BASE DADOS
CREATE DATABASE prova;
GO

-- UTILIZAÇÃO DA BASE
USE prova;
GO

-- CRIAÇÃO DA TABELA
CREATE TABLE TAREFAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO VARCHAR(500),
    PRIORIDADE INT NOT NULL,
    STATUS INT NOT NULL,
    DATA_CRIACAO DATETIME NOT NULL DEFAULT GETDATE(),
    DATA_CONCLUSAO DATETIME NULL
);
GO